### ISSUE TITLE
What is train list?

### ISSUE THREAD

**Issue by elsobhano** [xuyingzhongguo/deepfake_supcon#1]
parser.add_argument('--train_list', type=str,
                        default='/home/ubuntu/xuyi/Deepfake-Detection/data_list/test.txt',
                        help='path to custom dataset')

Would you please explain what the train list is?

**Comment by xuyingzhongguo** [comment]
Sure. It is a txt file that includes 'image_path label' every line.
Here is an example:
```
FaceForensics++/original_sequences/youtube/c23/face_images/870/frame121.png 0
FaceForensics++/manipulated_sequences/Deepfakes/c23/face_images/979_875/frame1.png 1
...
```

**Comment by elsobhano** [comment]
Thanks for your response, I have some other questions.
1. How many frames did you extracted from each video clip for your training dataset?
2.  How many frames did you extracted from each video clip for your test dataset?
3.  Are accuracies and results that you reported in your paper based on image level or video level?

**Comment by xuyingzhongguo** [comment]
1.2 I extracted a frame every 10 frames for both training and test. You could refer to [this code](https://github.com/xuyingzhongguo/DFDC_face_extract/blob/main/facenet_mtcnn_DFDC.py#:~:text=for%20i%2C,%3D%3D%201%3A).
3. In this paper, I only reported image level accuracy. While in this [paper](https://github.com/xuyingzhongguo/MCX-API) I reported both image level and frame level.
